# このサイト全体のタイトル
site_name: kayac-html5-starter

# meta description（og:description・twitter:descriptionでも使用）
description: kayac-html5-starter web page.

# meta keywords
keywords: []

ogp_type: website

# Facebookアプリのapp id（入れないとWarningが出る）
# facebook_app_id: 99999999999